defaults:
   - scope:
      path: ""
      type: "posts"
     values:
      layout: "posts"
   - scope:
      path: ""
     values:
      layout: "default"

author: "Ruhan Habib"
title: "Ruhan's Blog"
email: "ruhanhabib39@gmail.com"
description: "Solve interesting probs..."

timezone: "Asia/Dhaka"
